# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61068a4f1a799ce9fa7a8508ad7a09f61101a9eed0a4d381434e4cf53ffc735dd3883f763b8ef4add45119397c74b9733466e5788431ab9c3daf2b19fb22f50a

test:
  secret_key_base: 0cfd9d6c372c3dcba1758f3fec3b984f0a9b9cb0952c7584900cea6aee7733cd8e315a25c23d3f2f3c357668d08ad1847675f8fe2393859110c9c54cea80272e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
